export enum CharacterFormControls {
  ID = 'id',
  EXPANSION = 'expansion',
  NAME = 'name',
  DESCRIPTION = 'description',
  PROFESSION = 'profession',
  STARTING_LOCATION = 'starting_location',
  SANITY = 'sanity',
  ENDURANCE = 'endurance',
  CONCENTRATION = 'concentration',
  SKILLS = 'skills',
  ATTRIBUTES_SPEED = 'attributes_speed',
  ATTRIBUTES_SNEAK = 'attributes_sneak',
  ATTRIBUTES_PROWESS = 'attributes_prowess',
  ATTRIBUTES_WILL = 'attributes_will',
  ATTRIBUTES_KNOWLEDGE = 'attributes_knowledge',
  ATTRIBUTES_LUCK = 'attributes_luck',
  EQUIPMENT_MONEY = 'equipment_money',
  EQUIPMENT_CLUES = 'equipment_clues',
  EQUIPMENT_RANDOM_COMMON_ITEMS = 'equipment_random_common_items',
  EQUIPMENT_RANDOM_UNIQUE_ITEMS = 'equipment_random_unique_items',
  EQUIPMENT_RANDOM_SPELLS = 'equipment_random_spells',
  EQUIPMENT_RANDOM_ABILITIES = 'equipment_random_abilities',
  EQUIPMENT_RANDOM_ALLIES = 'equipment_random_allies',
  CARD_IDS = 'card_ids',
  IMAGE = 'image',
}
